- name: Setup Android SDK cmdline-tools
  run: |
    mkdir -p $ANDROID_HOME/cmdline-tools
    mkdir -p $ANDROID_HOME/tools/bin

    cd $ANDROID_HOME/cmdline-tools

    wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O tools.zip
    unzip tools.zip
    rm tools.zip

    mv cmdline-tools latest

    # Compatibilità Buildozer/Python-for-Android
    ln -s $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager $ANDROID_HOME/tools/bin/sdkmanager

      - name: Accept licenses
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Build APK
        run: |
          cd mobile
          cp ../protocol.py .
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: mobile/bin/*.apk